version: "3.9"
services:
  redis-server:
    image: "redis"
  node-app:
    build: .  # Look into current directory for a 'Dockerfile' and build that image
    ports:
      - "4001:8081" # First number is port number on your machine, and the second is the port inside the container